# Generated by Django 5.2 on 2025-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_avodha_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="img",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
